In [1]:
import numpy as np
import pandas as pd

import requests
from io import StringIO

import yfinance as yf

# Question 1: [IPO] Withdrawn IPOs by Company Type

In [2]:
url = "https://www.iposcoop.com/ipos-recently-filed/"
# headers = {'User-Agent': 'Mozilla/5.0'}
headers = {
    'User-Agent': (
        'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
        'AppleWebKit/537.36 (KHTML, like Gecko) '
        'Chrome/58.0.3029.110 Safari/537.3'
    )
}

html = requests.get(url, headers=headers, timeout=30)
html.raise_for_status()
df_recent_ipo = pd.read_html(StringIO(html.text))[0]

In [3]:
df_recent_ipo

,File Date,Company,Symbol,Managers,Shares (millions),Price Low,Price High,Est $ Vol (millions),Expected To Trade,SCOOP Rating
0,2026-09-24,ADARx Pharmaceuticals,ADRX,J.P.Morgan/Morgan Stanley/TD Cowen/UBS Investm...,26.25,$17.00,$17.00,$446.25,Priced,S/O
1,2026-09-24,Bluerock Acquisition Corp. II,BRRKU,BTIG,15.00,$10.00,$10.00,$150.00,Priced,S/O
2,2026-09-24,City Therapeutics,CTY,Goldman Sachs/Jefferies/Stifel/Oppenheimer & Co.,0.00,NaN,NaN,$100.00,TBA,S/O
3,2026-09-24,Hacker Interstellar,SOUD,Kingswood Capital Markets,3.90,$10.50,$11.50,$42.90,TBA,S/O
4,2026-09-24,New Iceland Arctic Acquisition Corp.,NIAAU,Chardan,12.50,$10.00,$10.00,$125.00,Week of,S/O
...,...,...,...,...,...,...,...,...,...,...
495,2026-01-05,Buda Juice,BUDA,MDB Capital Group,2.70,$7.50,$7.50,$20.03,Priced,S/O
496,2025-12-30,Optimal AI,TBA,R.F. Lafferty & Co.,2.50,$4.00,$5.00,$11.25,TBA,S/O
497,2025-12-29,Cafe Deco Group Ltd.,TBA,Kingswood Capital Markets,1.80,$6.00,$8.00,$12.60,TBA,S/O
498,2025-12-29,Riverstone Ltd.,DNJF,Joseph Gunnar,2.50,$5.00,$7.00,$15.00,TBA,S/O
499,2025-12-23,AOJE Inc.,AOJE,Revere Securities,0.00,NaN,NaN,$30.00,TBA,S/O

In [17]:
df_recent_ipo_filter = df_recent_ipo.loc[(df_recent_ipo["Expected To Trade"] == "Withdrawn") & (pd.to_datetime(df_recent_ipo["File Date"]) <= pd.Timestamp("2026-09-11"))].reset_index(drop=True)
df_recent_ipo_filter

,File Date,Company,Symbol,Managers,Shares (millions),Price Low,Price High,Est $ Vol (millions),Expected To Trade,SCOOP Rating
0,2026-09-10,Motive Technologies (Withdrawn),MTVE,J.P.Morgan/Citigroup/Barclays/Jefferies/RBC Ca...,0.00,NaN,NaN,$100.00,Withdrawn,S/O
1,2026-09-04,Idea Tech Holding (Withdrawn),IDTL,R.F. Lafferty & Co.,2.00,$4.00,$5.00,$9.00,Withdrawn,S/O
2,2026-09-01,Hornbeck Offshore Services (Withdrawn),HOS,J.P. Morgan/ Barclays/DNB Markets/Piper Sandle...,0.00,NaN,NaN,$100.00,Withdrawn,S/O
3,2026-08-31,Coolbit Technologies Ltd. (Withdrawn),CBAI,Eddid Securities USA,5.00,$4.00,$5.00,$22.50,Withdrawn,S/O
4,2026-08-27,Timber Road Acquisition Corp. (Withdrawn),TMRDU,Roth Capital Partners/Stone X Financial Inc.,20.00,$10.00,$10.00,$200.00,Withdrawn,S/O
5,2026-08-24,pan-Africa Corp. (Withdrawn),BLEUU,Santander,12.50,$10.00,$10.00,$125.00,Withdrawn,S/O
6,2026-08-18,Living Homeopathy (Withdrawn),LHI,Revere Securities,3.75,$4.00,$6.00,$19.00,Withdrawn,S/O
7,2026-07-31,Nuclea Energy (Withdrawn),NCLA,Joseph Gunnar & Co.,5.60,$8.00,$10.00,$50.40,Withdrawn,S/O
8,2026-07-10,APEX Global Solutions Ltd. (WITHDRAWN),APEX,US Tiger Securities,3.75,$4.00,$4.00,$15.00,Withdrawn,S/O
9,2026-07-08,Cloud Data Holdings (Withdrawn),CDN,Cathay Securities,3.75,$4.00,$4.50,$15.94,Withdrawn,S/O
10,2026-07-08,INFINT Acquisition Corp. 2 (Withdrawn),TBA,Roth Capital Partners,10.00,$10.00,$10.00,$100.00,Withdrawn,S/O
11,2026-06-24,Kilcoy Global Foods Ltd. (Withdrawn),KGF,Citigroup/Morgan Stanley,0.00,NaN,NaN,$100.00,Withdrawn,S/O
12,2026-06-24,Safepoint Holdings (Withdrawn),SFPT,Deutsche Bank Securities/Morgan Stanley/Keefe ...,16.67,$15.00,$17.00,$266.72,Withdrawn,S/O
13,2026-06-11,Club Versante Group Ltd.,CADV,Joseph Stone Capital,2.00,$4.00,$6.00,$10.00,Withdrawn,S/O
14,2026-06-10,Helio Corp. (NYSE-AmEx Uplisting – Unit Deal),HLEO,ThinkEquity,3.33,$4.00,$5.00,$15.00,Withdrawn,S/O
15,2026-06-01,Envoy Technologies (Withdrawn – Direct Listing),EVOY,Roth Capital Partners,7.80,$8.00,$8.00,$62.40,Withdrawn,S/O
16,2026-05-20,Vistek Limited (Withdrawn),VTEK,Bancroft Capital,6.25,$4.00,$6.00,$31.00,Withdrawn,S/O
17,2026-05-13,Ultratrex (Withdrawn),UTX,Craft Capital Management,1.25,$4.00,$6.00,$6.25,Withdrawn,S/O
18,2026-05-07,AiXin Life International,AIXN,Network 1 Financial Securities,2.38,$4.00,$4.00,$9.50,Withdrawn,S/O
19,2026-05-06,Xinxu Copper Industry Technology Ltd.,XXC,Craft Capital/ R.F. Lafferty & Co.,0.00,NaN,NaN,$15.00,Withdrawn,S/O
20,2026-05-05,EUPEC International Group Ltd.,EUPX,R.F. Lafferty & Co.,3.75,$4.00,$4.00,$15.00,Withdrawn,S/O
21,2026-05-01,CCIS Acquisition Corp.,CCACU,Benjamin Securities,6.00,$10.00,$10.00,$60.00,Withdrawn,S/O
22,2026-04-01,Going International Holding Company Limited,GIT,Prime Number Capital,0.00,NaN,NaN,$20.00,Withdrawn,S/O
23,2026-03-16,Firefly Automatix,FFLY,Roth Capital Markets/Lake Street Capital Markets,4.55,$4.50,$6.50,$25.00,Withdrawn,S/O
24,2026-03-06,Invea Therapeutics (Withdrawn),INAI,BofA Securities/ Citigroup/ Truist Securities,0.00,NaN,NaN,$75.00,Withdrawn,S/O
25,2026-02-27,Billion Group Holdings (Withdrawn),BGHL,American Trust Investment Services,1.50,$4.00,$6.00,$7.50,Withdrawn,S/O
26,2026-02-24,AIGO Holding Ltd.,AIGO,Eddid Securities USA,2.00,$4.00,$6.00,$10.00,Withdrawn,S/O
27,2026-02-19,Clear Street Group Inc. (Withdrawn),CLRS,Goldman Sachs/BofA Securities/Morgan Stanley/U...,13.00,$26.00,$28.00,$351.00,Withdrawn,S/O
28,2026-02-13,Lemeng Holdings (Withdrawn),LIAI,Prime Number Capital,4.00,$4.00,$6.00,$20.00,Withdrawn,S/O
29,2026-01-27,SFIDA X,SFDX,ThinkEquity,1.00,$5.00,$6.00,$5.50,Withdrawn,S/O
30,2026-01-06,"Altech Digital Co., Ltd.",ALD,Pacific Century Securities/Revere Securities,1.50,$4.00,$4.00,$6.00,Withdrawn,S/O

In [ ]:
import pandas as pd
import requests
from io import StringIO

def get_ipos_by_year(year: int) -> pd.DataFrame:
    """
    Fetch IPO data for the given year from stockanalysis.com.
    """
    url = f"https://stockanalysis.com/ipos/{year}/"
    headers = {
        'User-Agent': (
            'Mozilla/5.0 (Windows NT 10.0; Win64; x64) '
            'AppleWebKit/537.36 (KHTML, like Gecko) '
            'Chrome/58.0.3029.110 Safari/537.3'
        )
    }

    try:
        response = requests.get(url, headers=headers, timeout=10)
        response.raise_for_status()

        # Wrap HTML text in StringIO to avoid deprecation warning
        # "Passing literal html to 'read_html' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object."
        html_io = StringIO(response.text)
        tables = pd.read_html(html_io)

        if not tables:
            raise ValueError(f"No tables found for year {year}.")

        return tables[0]

    except requests.exceptions.RequestException as e:
        print(f"Request failed: {e}")
    except ValueError as ve:
        print(f"Data error: {ve}")
    except Exception as ex:
        print(f"Unexpected error: {ex}")

    return pd.DataFrame()